=== SAP-archive/yaas_java_jersey_wishlist/src/main/resources/api/wishlist.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title":"Wishlist",
  "type":"object",
  "properties":
  {
    "id":
    {
      "type":"string"
    },
    "url":
    {
      "type":"string",
      "format":"uri"
    },
    "owner":
    {
      "type":"string",
      "pattern":"^.+"
    },
    "title":
    {
      "type":"string",
      "pattern":"^.+"
    },
    "description":
    {
        "$ref" : "https://api.yaas.io/patterns/v1/schema-localized.json"
    },
    "createdAt":
    {
      "type":"string",
      "format":"date-time"
    },
    "items":
    {
      "type":"array",
      "items":
      {
        "$ref":"wishlistItem"
      }
    }
  },
  "required":["id","owner","title"]
}

=== SAP-archive/yaas_java_jersey_wishlist/src/main/resources/api/wishlists-example.json
[
  {
    "id":"98hw85Y945e6U358",
    "url":"http://myApi.de/wishlists/98hw85Y945e6U358",
    "owner":"345MWyh7w4hY98W6",
    "title":"Floyd's Birthday Wishlist",
    "description":"Bring on the presents:)",
    "createdAt":"2012-07-12T12:42:23.777Z",
    "items":
    [
      {
        "product":"yKsU0y+PQUPgTIYm",
        "amount":"1",
        "note":"Always wanted a Ferrari",
        "createdAt":"2012-07-12T13:23:31.415Z"
      },
      {
        "product":"ZdHErqRBhnJhJiVN",
        "amount":"4",
        "note":"Need some cool wheels for my new Ferrari",
        "createdAt":"2012-07-12T13:37:11.111Z"
      }
    ]
  },
  {
    "id":"CJNSo86m2N40E1nH",
    "url":"http://myApi.de/wishlists/CJNSo86m2N40E1nH",
    "owner":"LFB+LCqcc+XkztLM",
    "title":"Book's I'd like to read",
    "description":"If you're looking for a present for me, feel free to get me one of these...",
    "createdAt":"2014-10-01T23:99:00.555Z",
    "items":
    [
      {
        "product":"NrJSCL4TTqfWNHs4",
        "amount":"1",
        "note":"My favorite author's newest book!",
        "createdAt":"2014-10-01T23:99:00.555Z"
      }
    ]
  }
]

=== SAP-archive/yaas_java_jersey_wishlist/src/main/resources/api/wishlist-example.json
{
  "id":"98hw85Y945e6U358",
  "url":"http://myApi.de/wishlists/98hw85Y945e6U358",
  "owner":"345MWyh7w4hY98W6",
  "title":"Floyd's Birthday Wishlist",
  "description":"Bring on the presents:)",
  "createdAt":"2012-07-12T12:42:23.777Z",
  "items":
  [
    {
      "product":"yKsU0y+PQUPgTIYm",
      "amount":"1",
      "note":"Always wanted a Ferrari",
      "createdAt":"2012-07-12T13:23:31.415Z"
    },
    {
      "product":"ZdHErqRBhnJhJiVN",
      "amount":"4",
      "note":"Need some cool wheels for my new Ferrari",
      "createdAt":"2012-07-12T13:37:11.111Z"
    }
  ]
}
